### PR TITLE
release virtio-queue v0.6.0

### PR DESCRIPTION
**Pull request by slp**

### CODE REVIEW

**Review by stsquad — DISMISSED** [review]

**Comment by stsquad** [comment]
Hmm not sure why the autotest is failing....

**Comment by vireshk** [comment]
I think these need to be updated as well since they refer to local crate ?

crates/devices/virtio-console/Cargo.toml:virtio-queue = { path = "../../virtio-queue", version = "0.5.0" }
crates/devices/virtio-vsock/Cargo.toml:virtio-queue = { path = "../../virtio-queue", version = "0.5.0" }
crates/devices/virtio-vsock/Cargo.toml:virtio-queue = { path = "../../virtio-queue", version = "0.5.0", features = ["test-utils"] }
crates/virtio-device/Cargo.toml:virtio-queue = { path = "../virtio-queue", version = "0.5.0"}
crates/virtio-queue-ser/Cargo.toml:virtio-queue = { path = "../../crates/virtio-queue", version = "0.5.0" }

**Comment by andreeaflorescu** [comment]
> I think these need to be updated as well since they refer to local crate ?

Indeed, we need to update the version they depend on to be the latest one that we want to release because otherwise there is a mismatch between local builds and crates.io versions.

**Comment by slp** [comment]
You're right, I'll wait for https://github.com/rust-vmm/vm-virtio/pull/190 to get merged, rebase this one and fix it.

**Comment by andreeaflorescu** [comment]
> You're right, I'll wait for #190 to get merged, rebase this one and fix it.

#190 is merged.

**Review by andreeaflorescu — APPROVED** [review]

**Review by stsquad — APPROVED** [review]

**Pull request merged**
